/*
Horizon Server API

Welcome to the Horizon Server API Reference documentation. This API reference provides comprehensive information about status of all Horizon Server components and resources. <br> Choose Latest spec from dropdown to view API reference on latest version available.

API version: 2212
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gohorizon

import (
	"encoding/json"
)

// checks if the ResumeTaskSpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResumeTaskSpec{}

// ResumeTaskSpec Information required for resuming a task.
type ResumeTaskSpec struct {
	// Indicates whether to restart the task for virtual machines whose task status is in error state. Default value is false.
	RetryFailedVms *bool `json:"retry_failed_vms,omitempty"`
	// Indicates whether to stop the task at first error. Default value is true.
	StopOnError *bool `json:"stop_on_error,omitempty"`
}

// NewResumeTaskSpec instantiates a new ResumeTaskSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResumeTaskSpec() *ResumeTaskSpec {
	this := ResumeTaskSpec{}
	return &this
}

// NewResumeTaskSpecWithDefaults instantiates a new ResumeTaskSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResumeTaskSpecWithDefaults() *ResumeTaskSpec {
	this := ResumeTaskSpec{}
	return &this
}

// GetRetryFailedVms returns the RetryFailedVms field value if set, zero value otherwise.
func (o *ResumeTaskSpec) GetRetryFailedVms() bool {
	if o == nil || IsNil(o.RetryFailedVms) {
		var ret bool
		return ret
	}
	return *o.RetryFailedVms
}

// GetRetryFailedVmsOk returns a tuple with the RetryFailedVms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResumeTaskSpec) GetRetryFailedVmsOk() (*bool, bool) {
	if o == nil || IsNil(o.RetryFailedVms) {
		return nil, false
	}
	return o.RetryFailedVms, true
}

// HasRetryFailedVms returns a boolean if a field has been set.
func (o *ResumeTaskSpec) HasRetryFailedVms() bool {
	if o != nil && !IsNil(o.RetryFailedVms) {
		return true
	}

	return false
}

// SetRetryFailedVms gets a reference to the given bool and assigns it to the RetryFailedVms field.
func (o *ResumeTaskSpec) SetRetryFailedVms(v bool) {
	o.RetryFailedVms = &v
}

// GetStopOnError returns the StopOnError field value if set, zero value otherwise.
func (o *ResumeTaskSpec) GetStopOnError() bool {
	if o == nil || IsNil(o.StopOnError) {
		var ret bool
		return ret
	}
	return *o.StopOnError
}

// GetStopOnErrorOk returns a tuple with the StopOnError field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResumeTaskSpec) GetStopOnErrorOk() (*bool, bool) {
	if o == nil || IsNil(o.StopOnError) {
		return nil, false
	}
	return o.StopOnError, true
}

// HasStopOnError returns a boolean if a field has been set.
func (o *ResumeTaskSpec) HasStopOnError() bool {
	if o != nil && !IsNil(o.StopOnError) {
		return true
	}

	return false
}

// SetStopOnError gets a reference to the given bool and assigns it to the StopOnError field.
func (o *ResumeTaskSpec) SetStopOnError(v bool) {
	o.StopOnError = &v
}

func (o ResumeTaskSpec) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResumeTaskSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RetryFailedVms) {
		toSerialize["retry_failed_vms"] = o.RetryFailedVms
	}
	if !IsNil(o.StopOnError) {
		toSerialize["stop_on_error"] = o.StopOnError
	}
	return toSerialize, nil
}

type NullableResumeTaskSpec struct {
	value *ResumeTaskSpec
	isSet bool
}

func (v NullableResumeTaskSpec) Get() *ResumeTaskSpec {
	return v.value
}

func (v *NullableResumeTaskSpec) Set(val *ResumeTaskSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableResumeTaskSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableResumeTaskSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResumeTaskSpec(val *ResumeTaskSpec) *NullableResumeTaskSpec {
	return &NullableResumeTaskSpec{value: val, isSet: true}
}

func (v NullableResumeTaskSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResumeTaskSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


