/*
Horizon Server API

Welcome to the Horizon Server API Reference documentation. This API reference provides comprehensive information about status of all Horizon Server components and resources. <br> Choose Latest spec from dropdown to view API reference on latest version available.

API version: 2212
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gohorizon

import (
	"encoding/json"
)

// checks if the ServerProperties type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServerProperties{}

// ServerProperties Server properties of Security configuration.
type ServerProperties struct {
	// List of cipher suites of server.
	CipherSuites []string `json:"cipher_suites,omitempty"`
	// List of named groups of server.
	NamedGroups []string `json:"named_groups,omitempty"`
	// List of signature algorithms of server.
	SignatureAlgorithms []string `json:"signature_algorithms,omitempty"`
	// List of thumbprint algorithms of server.
	ThumbprintAlgorithms []string `json:"thumbprint_algorithms,omitempty"`
}

// NewServerProperties instantiates a new ServerProperties object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServerProperties() *ServerProperties {
	this := ServerProperties{}
	return &this
}

// NewServerPropertiesWithDefaults instantiates a new ServerProperties object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServerPropertiesWithDefaults() *ServerProperties {
	this := ServerProperties{}
	return &this
}

// GetCipherSuites returns the CipherSuites field value if set, zero value otherwise.
func (o *ServerProperties) GetCipherSuites() []string {
	if o == nil || IsNil(o.CipherSuites) {
		var ret []string
		return ret
	}
	return o.CipherSuites
}

// GetCipherSuitesOk returns a tuple with the CipherSuites field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerProperties) GetCipherSuitesOk() ([]string, bool) {
	if o == nil || IsNil(o.CipherSuites) {
		return nil, false
	}
	return o.CipherSuites, true
}

// HasCipherSuites returns a boolean if a field has been set.
func (o *ServerProperties) HasCipherSuites() bool {
	if o != nil && !IsNil(o.CipherSuites) {
		return true
	}

	return false
}

// SetCipherSuites gets a reference to the given []string and assigns it to the CipherSuites field.
func (o *ServerProperties) SetCipherSuites(v []string) {
	o.CipherSuites = v
}

// GetNamedGroups returns the NamedGroups field value if set, zero value otherwise.
func (o *ServerProperties) GetNamedGroups() []string {
	if o == nil || IsNil(o.NamedGroups) {
		var ret []string
		return ret
	}
	return o.NamedGroups
}

// GetNamedGroupsOk returns a tuple with the NamedGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerProperties) GetNamedGroupsOk() ([]string, bool) {
	if o == nil || IsNil(o.NamedGroups) {
		return nil, false
	}
	return o.NamedGroups, true
}

// HasNamedGroups returns a boolean if a field has been set.
func (o *ServerProperties) HasNamedGroups() bool {
	if o != nil && !IsNil(o.NamedGroups) {
		return true
	}

	return false
}

// SetNamedGroups gets a reference to the given []string and assigns it to the NamedGroups field.
func (o *ServerProperties) SetNamedGroups(v []string) {
	o.NamedGroups = v
}

// GetSignatureAlgorithms returns the SignatureAlgorithms field value if set, zero value otherwise.
func (o *ServerProperties) GetSignatureAlgorithms() []string {
	if o == nil || IsNil(o.SignatureAlgorithms) {
		var ret []string
		return ret
	}
	return o.SignatureAlgorithms
}

// GetSignatureAlgorithmsOk returns a tuple with the SignatureAlgorithms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerProperties) GetSignatureAlgorithmsOk() ([]string, bool) {
	if o == nil || IsNil(o.SignatureAlgorithms) {
		return nil, false
	}
	return o.SignatureAlgorithms, true
}

// HasSignatureAlgorithms returns a boolean if a field has been set.
func (o *ServerProperties) HasSignatureAlgorithms() bool {
	if o != nil && !IsNil(o.SignatureAlgorithms) {
		return true
	}

	return false
}

// SetSignatureAlgorithms gets a reference to the given []string and assigns it to the SignatureAlgorithms field.
func (o *ServerProperties) SetSignatureAlgorithms(v []string) {
	o.SignatureAlgorithms = v
}

// GetThumbprintAlgorithms returns the ThumbprintAlgorithms field value if set, zero value otherwise.
func (o *ServerProperties) GetThumbprintAlgorithms() []string {
	if o == nil || IsNil(o.ThumbprintAlgorithms) {
		var ret []string
		return ret
	}
	return o.ThumbprintAlgorithms
}

// GetThumbprintAlgorithmsOk returns a tuple with the ThumbprintAlgorithms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerProperties) GetThumbprintAlgorithmsOk() ([]string, bool) {
	if o == nil || IsNil(o.ThumbprintAlgorithms) {
		return nil, false
	}
	return o.ThumbprintAlgorithms, true
}

// HasThumbprintAlgorithms returns a boolean if a field has been set.
func (o *ServerProperties) HasThumbprintAlgorithms() bool {
	if o != nil && !IsNil(o.ThumbprintAlgorithms) {
		return true
	}

	return false
}

// SetThumbprintAlgorithms gets a reference to the given []string and assigns it to the ThumbprintAlgorithms field.
func (o *ServerProperties) SetThumbprintAlgorithms(v []string) {
	o.ThumbprintAlgorithms = v
}

func (o ServerProperties) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServerProperties) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CipherSuites) {
		toSerialize["cipher_suites"] = o.CipherSuites
	}
	if !IsNil(o.NamedGroups) {
		toSerialize["named_groups"] = o.NamedGroups
	}
	if !IsNil(o.SignatureAlgorithms) {
		toSerialize["signature_algorithms"] = o.SignatureAlgorithms
	}
	if !IsNil(o.ThumbprintAlgorithms) {
		toSerialize["thumbprint_algorithms"] = o.ThumbprintAlgorithms
	}
	return toSerialize, nil
}

type NullableServerProperties struct {
	value *ServerProperties
	isSet bool
}

func (v NullableServerProperties) Get() *ServerProperties {
	return v.value
}

func (v *NullableServerProperties) Set(val *ServerProperties) {
	v.value = val
	v.isSet = true
}

func (v NullableServerProperties) IsSet() bool {
	return v.isSet
}

func (v *NullableServerProperties) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServerProperties(val *ServerProperties) *NullableServerProperties {
	return &NullableServerProperties{value: val, isSet: true}
}

func (v NullableServerProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServerProperties) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


