/*
Horizon Server API

Welcome to the Horizon Server API Reference documentation. This API reference provides comprehensive information about status of all Horizon Server components and resources. <br> Choose Latest spec from dropdown to view API reference on latest version available.

API version: 2212
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gohorizon

import (
	"encoding/json"
)

// checks if the FarmSessionSettingsCreateSpecV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FarmSessionSettingsCreateSpecV2{}

// FarmSessionSettingsCreateSpecV2 Session settings related to the Farm.
type FarmSessionSettingsCreateSpecV2 struct {
	// Disconnected sessions timeout (in minutes). An empty disconnected session is logged off after the timeout. This is required if the disconnect_session_timeout_policy is set to AFTER.
	DisconnectedSessionTimeoutMinutes *int32 `json:"disconnected_session_timeout_minutes,omitempty"`
	// Log-off policy after disconnected session. Default value is NEVER.  * IMMEDIATELY: Immediately Logoff after user disconnect. * AFTER: Logoff after the specified number of minutes after user disconnect. * NEVER: Do not logoff after user disconnect.
	DisconnectedSessionTimeoutPolicy *string `json:"disconnected_session_timeout_policy,omitempty"`
	// Application empty session timeout (in minutes). An empty session (that has no remote-able window) is disconnected after the timeout. Default value is 1. This is required if the empty_session_timeout_policy is set to AFTER.
	EmptySessionTimeoutMinutes *int32 `json:"empty_session_timeout_minutes,omitempty"`
	// Application empty session timeout policy. Default value is AFTER * IMMEDIATE: Empty session will be disconnected immediately. * NEVER: Empty session will never disconnected. * AFTER: Empty session will be disconnected after specified number of minutes.
	EmptySessionTimeoutPolicy *string `json:"empty_session_timeout_policy,omitempty"`
	// Indicates whether the empty application sessions are logged off (true) or disconnected (false) after timeout. Default value is false if emptySessionTimeoutPolicy is set to AFTER or IMMEDIATE.
	LogoffAfterTimeout *bool `json:"logoff_after_timeout,omitempty"`
	// Application pre-launch session timeout (in minutes). A pre-launch session is disconnected after the timeout. Default value is 10. This is required if pre_launch_session_timeout_policy is set to AFTER.
	PreLaunchSessionTimeoutMinutes *int32 `json:"pre_launch_session_timeout_minutes,omitempty"`
	// Application pre-launch session timeout policy. Default value is AFTER * AFTER: Pre-launched session is disconnected after specified number of minutes. * NEVER: Pre-launched session is never disconnected.
	PreLaunchSessionTimeoutPolicy *string `json:"pre_launch_session_timeout_policy,omitempty"`
	// Specifies the session timeout policy for the applications published from the Farm. This policy indicates whether the launched application session is a forever application session or not. Default value is DEFAULT. * DEFAULT: Indicates application sessions will be disconnected either on reaching the global idle timeout or on reaching the max session timeout. * NEVER: Indicates application sessions will not be disconnected either on reaching the global idle timeout or on reaching the max session timeout.
	SessionTimeoutPolicy *string `json:"session_timeout_policy,omitempty"`
}

// NewFarmSessionSettingsCreateSpecV2 instantiates a new FarmSessionSettingsCreateSpecV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFarmSessionSettingsCreateSpecV2() *FarmSessionSettingsCreateSpecV2 {
	this := FarmSessionSettingsCreateSpecV2{}
	return &this
}

// NewFarmSessionSettingsCreateSpecV2WithDefaults instantiates a new FarmSessionSettingsCreateSpecV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFarmSessionSettingsCreateSpecV2WithDefaults() *FarmSessionSettingsCreateSpecV2 {
	this := FarmSessionSettingsCreateSpecV2{}
	return &this
}

// GetDisconnectedSessionTimeoutMinutes returns the DisconnectedSessionTimeoutMinutes field value if set, zero value otherwise.
func (o *FarmSessionSettingsCreateSpecV2) GetDisconnectedSessionTimeoutMinutes() int32 {
	if o == nil || IsNil(o.DisconnectedSessionTimeoutMinutes) {
		var ret int32
		return ret
	}
	return *o.DisconnectedSessionTimeoutMinutes
}

// GetDisconnectedSessionTimeoutMinutesOk returns a tuple with the DisconnectedSessionTimeoutMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FarmSessionSettingsCreateSpecV2) GetDisconnectedSessionTimeoutMinutesOk() (*int32, bool) {
	if o == nil || IsNil(o.DisconnectedSessionTimeoutMinutes) {
		return nil, false
	}
	return o.DisconnectedSessionTimeoutMinutes, true
}

// HasDisconnectedSessionTimeoutMinutes returns a boolean if a field has been set.
func (o *FarmSessionSettingsCreateSpecV2) HasDisconnectedSessionTimeoutMinutes() bool {
	if o != nil && !IsNil(o.DisconnectedSessionTimeoutMinutes) {
		return true
	}

	return false
}

// SetDisconnectedSessionTimeoutMinutes gets a reference to the given int32 and assigns it to the DisconnectedSessionTimeoutMinutes field.
func (o *FarmSessionSettingsCreateSpecV2) SetDisconnectedSessionTimeoutMinutes(v int32) {
	o.DisconnectedSessionTimeoutMinutes = &v
}

// GetDisconnectedSessionTimeoutPolicy returns the DisconnectedSessionTimeoutPolicy field value if set, zero value otherwise.
func (o *FarmSessionSettingsCreateSpecV2) GetDisconnectedSessionTimeoutPolicy() string {
	if o == nil || IsNil(o.DisconnectedSessionTimeoutPolicy) {
		var ret string
		return ret
	}
	return *o.DisconnectedSessionTimeoutPolicy
}

// GetDisconnectedSessionTimeoutPolicyOk returns a tuple with the DisconnectedSessionTimeoutPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FarmSessionSettingsCreateSpecV2) GetDisconnectedSessionTimeoutPolicyOk() (*string, bool) {
	if o == nil || IsNil(o.DisconnectedSessionTimeoutPolicy) {
		return nil, false
	}
	return o.DisconnectedSessionTimeoutPolicy, true
}

// HasDisconnectedSessionTimeoutPolicy returns a boolean if a field has been set.
func (o *FarmSessionSettingsCreateSpecV2) HasDisconnectedSessionTimeoutPolicy() bool {
	if o != nil && !IsNil(o.DisconnectedSessionTimeoutPolicy) {
		return true
	}

	return false
}

// SetDisconnectedSessionTimeoutPolicy gets a reference to the given string and assigns it to the DisconnectedSessionTimeoutPolicy field.
func (o *FarmSessionSettingsCreateSpecV2) SetDisconnectedSessionTimeoutPolicy(v string) {
	o.DisconnectedSessionTimeoutPolicy = &v
}

// GetEmptySessionTimeoutMinutes returns the EmptySessionTimeoutMinutes field value if set, zero value otherwise.
func (o *FarmSessionSettingsCreateSpecV2) GetEmptySessionTimeoutMinutes() int32 {
	if o == nil || IsNil(o.EmptySessionTimeoutMinutes) {
		var ret int32
		return ret
	}
	return *o.EmptySessionTimeoutMinutes
}

// GetEmptySessionTimeoutMinutesOk returns a tuple with the EmptySessionTimeoutMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FarmSessionSettingsCreateSpecV2) GetEmptySessionTimeoutMinutesOk() (*int32, bool) {
	if o == nil || IsNil(o.EmptySessionTimeoutMinutes) {
		return nil, false
	}
	return o.EmptySessionTimeoutMinutes, true
}

// HasEmptySessionTimeoutMinutes returns a boolean if a field has been set.
func (o *FarmSessionSettingsCreateSpecV2) HasEmptySessionTimeoutMinutes() bool {
	if o != nil && !IsNil(o.EmptySessionTimeoutMinutes) {
		return true
	}

	return false
}

// SetEmptySessionTimeoutMinutes gets a reference to the given int32 and assigns it to the EmptySessionTimeoutMinutes field.
func (o *FarmSessionSettingsCreateSpecV2) SetEmptySessionTimeoutMinutes(v int32) {
	o.EmptySessionTimeoutMinutes = &v
}

// GetEmptySessionTimeoutPolicy returns the EmptySessionTimeoutPolicy field value if set, zero value otherwise.
func (o *FarmSessionSettingsCreateSpecV2) GetEmptySessionTimeoutPolicy() string {
	if o == nil || IsNil(o.EmptySessionTimeoutPolicy) {
		var ret string
		return ret
	}
	return *o.EmptySessionTimeoutPolicy
}

// GetEmptySessionTimeoutPolicyOk returns a tuple with the EmptySessionTimeoutPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FarmSessionSettingsCreateSpecV2) GetEmptySessionTimeoutPolicyOk() (*string, bool) {
	if o == nil || IsNil(o.EmptySessionTimeoutPolicy) {
		return nil, false
	}
	return o.EmptySessionTimeoutPolicy, true
}

// HasEmptySessionTimeoutPolicy returns a boolean if a field has been set.
func (o *FarmSessionSettingsCreateSpecV2) HasEmptySessionTimeoutPolicy() bool {
	if o != nil && !IsNil(o.EmptySessionTimeoutPolicy) {
		return true
	}

	return false
}

// SetEmptySessionTimeoutPolicy gets a reference to the given string and assigns it to the EmptySessionTimeoutPolicy field.
func (o *FarmSessionSettingsCreateSpecV2) SetEmptySessionTimeoutPolicy(v string) {
	o.EmptySessionTimeoutPolicy = &v
}

// GetLogoffAfterTimeout returns the LogoffAfterTimeout field value if set, zero value otherwise.
func (o *FarmSessionSettingsCreateSpecV2) GetLogoffAfterTimeout() bool {
	if o == nil || IsNil(o.LogoffAfterTimeout) {
		var ret bool
		return ret
	}
	return *o.LogoffAfterTimeout
}

// GetLogoffAfterTimeoutOk returns a tuple with the LogoffAfterTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FarmSessionSettingsCreateSpecV2) GetLogoffAfterTimeoutOk() (*bool, bool) {
	if o == nil || IsNil(o.LogoffAfterTimeout) {
		return nil, false
	}
	return o.LogoffAfterTimeout, true
}

// HasLogoffAfterTimeout returns a boolean if a field has been set.
func (o *FarmSessionSettingsCreateSpecV2) HasLogoffAfterTimeout() bool {
	if o != nil && !IsNil(o.LogoffAfterTimeout) {
		return true
	}

	return false
}

// SetLogoffAfterTimeout gets a reference to the given bool and assigns it to the LogoffAfterTimeout field.
func (o *FarmSessionSettingsCreateSpecV2) SetLogoffAfterTimeout(v bool) {
	o.LogoffAfterTimeout = &v
}

// GetPreLaunchSessionTimeoutMinutes returns the PreLaunchSessionTimeoutMinutes field value if set, zero value otherwise.
func (o *FarmSessionSettingsCreateSpecV2) GetPreLaunchSessionTimeoutMinutes() int32 {
	if o == nil || IsNil(o.PreLaunchSessionTimeoutMinutes) {
		var ret int32
		return ret
	}
	return *o.PreLaunchSessionTimeoutMinutes
}

// GetPreLaunchSessionTimeoutMinutesOk returns a tuple with the PreLaunchSessionTimeoutMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FarmSessionSettingsCreateSpecV2) GetPreLaunchSessionTimeoutMinutesOk() (*int32, bool) {
	if o == nil || IsNil(o.PreLaunchSessionTimeoutMinutes) {
		return nil, false
	}
	return o.PreLaunchSessionTimeoutMinutes, true
}

// HasPreLaunchSessionTimeoutMinutes returns a boolean if a field has been set.
func (o *FarmSessionSettingsCreateSpecV2) HasPreLaunchSessionTimeoutMinutes() bool {
	if o != nil && !IsNil(o.PreLaunchSessionTimeoutMinutes) {
		return true
	}

	return false
}

// SetPreLaunchSessionTimeoutMinutes gets a reference to the given int32 and assigns it to the PreLaunchSessionTimeoutMinutes field.
func (o *FarmSessionSettingsCreateSpecV2) SetPreLaunchSessionTimeoutMinutes(v int32) {
	o.PreLaunchSessionTimeoutMinutes = &v
}

// GetPreLaunchSessionTimeoutPolicy returns the PreLaunchSessionTimeoutPolicy field value if set, zero value otherwise.
func (o *FarmSessionSettingsCreateSpecV2) GetPreLaunchSessionTimeoutPolicy() string {
	if o == nil || IsNil(o.PreLaunchSessionTimeoutPolicy) {
		var ret string
		return ret
	}
	return *o.PreLaunchSessionTimeoutPolicy
}

// GetPreLaunchSessionTimeoutPolicyOk returns a tuple with the PreLaunchSessionTimeoutPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FarmSessionSettingsCreateSpecV2) GetPreLaunchSessionTimeoutPolicyOk() (*string, bool) {
	if o == nil || IsNil(o.PreLaunchSessionTimeoutPolicy) {
		return nil, false
	}
	return o.PreLaunchSessionTimeoutPolicy, true
}

// HasPreLaunchSessionTimeoutPolicy returns a boolean if a field has been set.
func (o *FarmSessionSettingsCreateSpecV2) HasPreLaunchSessionTimeoutPolicy() bool {
	if o != nil && !IsNil(o.PreLaunchSessionTimeoutPolicy) {
		return true
	}

	return false
}

// SetPreLaunchSessionTimeoutPolicy gets a reference to the given string and assigns it to the PreLaunchSessionTimeoutPolicy field.
func (o *FarmSessionSettingsCreateSpecV2) SetPreLaunchSessionTimeoutPolicy(v string) {
	o.PreLaunchSessionTimeoutPolicy = &v
}

// GetSessionTimeoutPolicy returns the SessionTimeoutPolicy field value if set, zero value otherwise.
func (o *FarmSessionSettingsCreateSpecV2) GetSessionTimeoutPolicy() string {
	if o == nil || IsNil(o.SessionTimeoutPolicy) {
		var ret string
		return ret
	}
	return *o.SessionTimeoutPolicy
}

// GetSessionTimeoutPolicyOk returns a tuple with the SessionTimeoutPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FarmSessionSettingsCreateSpecV2) GetSessionTimeoutPolicyOk() (*string, bool) {
	if o == nil || IsNil(o.SessionTimeoutPolicy) {
		return nil, false
	}
	return o.SessionTimeoutPolicy, true
}

// HasSessionTimeoutPolicy returns a boolean if a field has been set.
func (o *FarmSessionSettingsCreateSpecV2) HasSessionTimeoutPolicy() bool {
	if o != nil && !IsNil(o.SessionTimeoutPolicy) {
		return true
	}

	return false
}

// SetSessionTimeoutPolicy gets a reference to the given string and assigns it to the SessionTimeoutPolicy field.
func (o *FarmSessionSettingsCreateSpecV2) SetSessionTimeoutPolicy(v string) {
	o.SessionTimeoutPolicy = &v
}

func (o FarmSessionSettingsCreateSpecV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FarmSessionSettingsCreateSpecV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DisconnectedSessionTimeoutMinutes) {
		toSerialize["disconnected_session_timeout_minutes"] = o.DisconnectedSessionTimeoutMinutes
	}
	if !IsNil(o.DisconnectedSessionTimeoutPolicy) {
		toSerialize["disconnected_session_timeout_policy"] = o.DisconnectedSessionTimeoutPolicy
	}
	if !IsNil(o.EmptySessionTimeoutMinutes) {
		toSerialize["empty_session_timeout_minutes"] = o.EmptySessionTimeoutMinutes
	}
	if !IsNil(o.EmptySessionTimeoutPolicy) {
		toSerialize["empty_session_timeout_policy"] = o.EmptySessionTimeoutPolicy
	}
	if !IsNil(o.LogoffAfterTimeout) {
		toSerialize["logoff_after_timeout"] = o.LogoffAfterTimeout
	}
	if !IsNil(o.PreLaunchSessionTimeoutMinutes) {
		toSerialize["pre_launch_session_timeout_minutes"] = o.PreLaunchSessionTimeoutMinutes
	}
	if !IsNil(o.PreLaunchSessionTimeoutPolicy) {
		toSerialize["pre_launch_session_timeout_policy"] = o.PreLaunchSessionTimeoutPolicy
	}
	if !IsNil(o.SessionTimeoutPolicy) {
		toSerialize["session_timeout_policy"] = o.SessionTimeoutPolicy
	}
	return toSerialize, nil
}

type NullableFarmSessionSettingsCreateSpecV2 struct {
	value *FarmSessionSettingsCreateSpecV2
	isSet bool
}

func (v NullableFarmSessionSettingsCreateSpecV2) Get() *FarmSessionSettingsCreateSpecV2 {
	return v.value
}

func (v *NullableFarmSessionSettingsCreateSpecV2) Set(val *FarmSessionSettingsCreateSpecV2) {
	v.value = val
	v.isSet = true
}

func (v NullableFarmSessionSettingsCreateSpecV2) IsSet() bool {
	return v.isSet
}

func (v *NullableFarmSessionSettingsCreateSpecV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFarmSessionSettingsCreateSpecV2(val *FarmSessionSettingsCreateSpecV2) *NullableFarmSessionSettingsCreateSpecV2 {
	return &NullableFarmSessionSettingsCreateSpecV2{value: val, isSet: true}
}

func (v NullableFarmSessionSettingsCreateSpecV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFarmSessionSettingsCreateSpecV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


