/*
Horizon Server API

Welcome to the Horizon Server API Reference documentation. This API reference provides comprehensive information about status of all Horizon Server components and resources. <br> Choose Latest spec from dropdown to view API reference on latest version available.

API version: 2212
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gohorizon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InstantCloneDomainAccountUpdateSpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstantCloneDomainAccountUpdateSpec{}

// InstantCloneDomainAccountUpdateSpec Update specification for the instant clone domain account.
type InstantCloneDomainAccountUpdateSpec struct {
	// Password of the account.
	Password []string `json:"password"`
}

type _InstantCloneDomainAccountUpdateSpec InstantCloneDomainAccountUpdateSpec

// NewInstantCloneDomainAccountUpdateSpec instantiates a new InstantCloneDomainAccountUpdateSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstantCloneDomainAccountUpdateSpec(password []string) *InstantCloneDomainAccountUpdateSpec {
	this := InstantCloneDomainAccountUpdateSpec{}
	this.Password = password
	return &this
}

// NewInstantCloneDomainAccountUpdateSpecWithDefaults instantiates a new InstantCloneDomainAccountUpdateSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstantCloneDomainAccountUpdateSpecWithDefaults() *InstantCloneDomainAccountUpdateSpec {
	this := InstantCloneDomainAccountUpdateSpec{}
	return &this
}

// GetPassword returns the Password field value
func (o *InstantCloneDomainAccountUpdateSpec) GetPassword() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *InstantCloneDomainAccountUpdateSpec) GetPasswordOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Password, true
}

// SetPassword sets field value
func (o *InstantCloneDomainAccountUpdateSpec) SetPassword(v []string) {
	o.Password = v
}

func (o InstantCloneDomainAccountUpdateSpec) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstantCloneDomainAccountUpdateSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["password"] = o.Password
	return toSerialize, nil
}

func (o *InstantCloneDomainAccountUpdateSpec) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInstantCloneDomainAccountUpdateSpec := _InstantCloneDomainAccountUpdateSpec{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInstantCloneDomainAccountUpdateSpec)

	if err != nil {
		return err
	}

	*o = InstantCloneDomainAccountUpdateSpec(varInstantCloneDomainAccountUpdateSpec)

	return err
}

type NullableInstantCloneDomainAccountUpdateSpec struct {
	value *InstantCloneDomainAccountUpdateSpec
	isSet bool
}

func (v NullableInstantCloneDomainAccountUpdateSpec) Get() *InstantCloneDomainAccountUpdateSpec {
	return v.value
}

func (v *NullableInstantCloneDomainAccountUpdateSpec) Set(val *InstantCloneDomainAccountUpdateSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableInstantCloneDomainAccountUpdateSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableInstantCloneDomainAccountUpdateSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstantCloneDomainAccountUpdateSpec(val *InstantCloneDomainAccountUpdateSpec) *NullableInstantCloneDomainAccountUpdateSpec {
	return &NullableInstantCloneDomainAccountUpdateSpec{value: val, isSet: true}
}

func (v NullableInstantCloneDomainAccountUpdateSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstantCloneDomainAccountUpdateSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


