/*
Horizon Server API

Welcome to the Horizon Server API Reference documentation. This API reference provides comprehensive information about status of all Horizon Server components and resources. <br> Choose Latest spec from dropdown to view API reference on latest version available.

API version: 2212
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gohorizon

import (
	"encoding/json"
)

// checks if the SettingsInfoV3 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SettingsInfoV3{}

// SettingsInfoV3 Information related to Settings.
type SettingsInfoV3 struct {
	FeatureSettings *FeatureSettings `json:"feature_settings,omitempty"`
	GeneralSettings *GeneralSettingsV3 `json:"general_settings,omitempty"`
	SecuritySettings *SecuritySettingsV2 `json:"security_settings,omitempty"`
}

// NewSettingsInfoV3 instantiates a new SettingsInfoV3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSettingsInfoV3() *SettingsInfoV3 {
	this := SettingsInfoV3{}
	return &this
}

// NewSettingsInfoV3WithDefaults instantiates a new SettingsInfoV3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSettingsInfoV3WithDefaults() *SettingsInfoV3 {
	this := SettingsInfoV3{}
	return &this
}

// GetFeatureSettings returns the FeatureSettings field value if set, zero value otherwise.
func (o *SettingsInfoV3) GetFeatureSettings() FeatureSettings {
	if o == nil || IsNil(o.FeatureSettings) {
		var ret FeatureSettings
		return ret
	}
	return *o.FeatureSettings
}

// GetFeatureSettingsOk returns a tuple with the FeatureSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsInfoV3) GetFeatureSettingsOk() (*FeatureSettings, bool) {
	if o == nil || IsNil(o.FeatureSettings) {
		return nil, false
	}
	return o.FeatureSettings, true
}

// HasFeatureSettings returns a boolean if a field has been set.
func (o *SettingsInfoV3) HasFeatureSettings() bool {
	if o != nil && !IsNil(o.FeatureSettings) {
		return true
	}

	return false
}

// SetFeatureSettings gets a reference to the given FeatureSettings and assigns it to the FeatureSettings field.
func (o *SettingsInfoV3) SetFeatureSettings(v FeatureSettings) {
	o.FeatureSettings = &v
}

// GetGeneralSettings returns the GeneralSettings field value if set, zero value otherwise.
func (o *SettingsInfoV3) GetGeneralSettings() GeneralSettingsV3 {
	if o == nil || IsNil(o.GeneralSettings) {
		var ret GeneralSettingsV3
		return ret
	}
	return *o.GeneralSettings
}

// GetGeneralSettingsOk returns a tuple with the GeneralSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsInfoV3) GetGeneralSettingsOk() (*GeneralSettingsV3, bool) {
	if o == nil || IsNil(o.GeneralSettings) {
		return nil, false
	}
	return o.GeneralSettings, true
}

// HasGeneralSettings returns a boolean if a field has been set.
func (o *SettingsInfoV3) HasGeneralSettings() bool {
	if o != nil && !IsNil(o.GeneralSettings) {
		return true
	}

	return false
}

// SetGeneralSettings gets a reference to the given GeneralSettingsV3 and assigns it to the GeneralSettings field.
func (o *SettingsInfoV3) SetGeneralSettings(v GeneralSettingsV3) {
	o.GeneralSettings = &v
}

// GetSecuritySettings returns the SecuritySettings field value if set, zero value otherwise.
func (o *SettingsInfoV3) GetSecuritySettings() SecuritySettingsV2 {
	if o == nil || IsNil(o.SecuritySettings) {
		var ret SecuritySettingsV2
		return ret
	}
	return *o.SecuritySettings
}

// GetSecuritySettingsOk returns a tuple with the SecuritySettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsInfoV3) GetSecuritySettingsOk() (*SecuritySettingsV2, bool) {
	if o == nil || IsNil(o.SecuritySettings) {
		return nil, false
	}
	return o.SecuritySettings, true
}

// HasSecuritySettings returns a boolean if a field has been set.
func (o *SettingsInfoV3) HasSecuritySettings() bool {
	if o != nil && !IsNil(o.SecuritySettings) {
		return true
	}

	return false
}

// SetSecuritySettings gets a reference to the given SecuritySettingsV2 and assigns it to the SecuritySettings field.
func (o *SettingsInfoV3) SetSecuritySettings(v SecuritySettingsV2) {
	o.SecuritySettings = &v
}

func (o SettingsInfoV3) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SettingsInfoV3) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FeatureSettings) {
		toSerialize["feature_settings"] = o.FeatureSettings
	}
	if !IsNil(o.GeneralSettings) {
		toSerialize["general_settings"] = o.GeneralSettings
	}
	if !IsNil(o.SecuritySettings) {
		toSerialize["security_settings"] = o.SecuritySettings
	}
	return toSerialize, nil
}

type NullableSettingsInfoV3 struct {
	value *SettingsInfoV3
	isSet bool
}

func (v NullableSettingsInfoV3) Get() *SettingsInfoV3 {
	return v.value
}

func (v *NullableSettingsInfoV3) Set(val *SettingsInfoV3) {
	v.value = val
	v.isSet = true
}

func (v NullableSettingsInfoV3) IsSet() bool {
	return v.isSet
}

func (v *NullableSettingsInfoV3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSettingsInfoV3(val *SettingsInfoV3) *NullableSettingsInfoV3 {
	return &NullableSettingsInfoV3{value: val, isSet: true}
}

func (v NullableSettingsInfoV3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSettingsInfoV3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


