/*
Horizon Server API

Welcome to the Horizon Server API Reference documentation. This API reference provides comprehensive information about status of all Horizon Server components and resources. <br> Choose Latest spec from dropdown to view API reference on latest version available.

API version: 2212
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gohorizon

import (
	"encoding/json"
)

// checks if the DesktopPoolQuickprepCustomizationSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DesktopPoolQuickprepCustomizationSettings{}

// DesktopPoolQuickprepCustomizationSettings Settings for QuickPrep customization.
type DesktopPoolQuickprepCustomizationSettings struct {
	// Post synchronization script parameters.
	PostSynchronizationScriptParameters *string `json:"post_synchronization_script_parameters,omitempty"`
	// Post synchronization script. QuickPrep can run a customization script on linked-clone machines after they are created, recomposed, and refreshed. Provide the path to the script on the parent virtual machine.
	PostSynchronizationScriptPath *string `json:"post_synchronization_script_path,omitempty"`
	// Power off script parameters.
	PowerOffScriptParameters *string `json:"power_off_script_parameters,omitempty"`
	// Power off script. QuickPrep can run a customization script on linked-clone machines before they are powered off. Provide the path to the script on the parent virtual machine.
	PowerOffScriptPath *string `json:"power_off_script_path,omitempty"`
}

// NewDesktopPoolQuickprepCustomizationSettings instantiates a new DesktopPoolQuickprepCustomizationSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDesktopPoolQuickprepCustomizationSettings() *DesktopPoolQuickprepCustomizationSettings {
	this := DesktopPoolQuickprepCustomizationSettings{}
	return &this
}

// NewDesktopPoolQuickprepCustomizationSettingsWithDefaults instantiates a new DesktopPoolQuickprepCustomizationSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDesktopPoolQuickprepCustomizationSettingsWithDefaults() *DesktopPoolQuickprepCustomizationSettings {
	this := DesktopPoolQuickprepCustomizationSettings{}
	return &this
}

// GetPostSynchronizationScriptParameters returns the PostSynchronizationScriptParameters field value if set, zero value otherwise.
func (o *DesktopPoolQuickprepCustomizationSettings) GetPostSynchronizationScriptParameters() string {
	if o == nil || IsNil(o.PostSynchronizationScriptParameters) {
		var ret string
		return ret
	}
	return *o.PostSynchronizationScriptParameters
}

// GetPostSynchronizationScriptParametersOk returns a tuple with the PostSynchronizationScriptParameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DesktopPoolQuickprepCustomizationSettings) GetPostSynchronizationScriptParametersOk() (*string, bool) {
	if o == nil || IsNil(o.PostSynchronizationScriptParameters) {
		return nil, false
	}
	return o.PostSynchronizationScriptParameters, true
}

// HasPostSynchronizationScriptParameters returns a boolean if a field has been set.
func (o *DesktopPoolQuickprepCustomizationSettings) HasPostSynchronizationScriptParameters() bool {
	if o != nil && !IsNil(o.PostSynchronizationScriptParameters) {
		return true
	}

	return false
}

// SetPostSynchronizationScriptParameters gets a reference to the given string and assigns it to the PostSynchronizationScriptParameters field.
func (o *DesktopPoolQuickprepCustomizationSettings) SetPostSynchronizationScriptParameters(v string) {
	o.PostSynchronizationScriptParameters = &v
}

// GetPostSynchronizationScriptPath returns the PostSynchronizationScriptPath field value if set, zero value otherwise.
func (o *DesktopPoolQuickprepCustomizationSettings) GetPostSynchronizationScriptPath() string {
	if o == nil || IsNil(o.PostSynchronizationScriptPath) {
		var ret string
		return ret
	}
	return *o.PostSynchronizationScriptPath
}

// GetPostSynchronizationScriptPathOk returns a tuple with the PostSynchronizationScriptPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DesktopPoolQuickprepCustomizationSettings) GetPostSynchronizationScriptPathOk() (*string, bool) {
	if o == nil || IsNil(o.PostSynchronizationScriptPath) {
		return nil, false
	}
	return o.PostSynchronizationScriptPath, true
}

// HasPostSynchronizationScriptPath returns a boolean if a field has been set.
func (o *DesktopPoolQuickprepCustomizationSettings) HasPostSynchronizationScriptPath() bool {
	if o != nil && !IsNil(o.PostSynchronizationScriptPath) {
		return true
	}

	return false
}

// SetPostSynchronizationScriptPath gets a reference to the given string and assigns it to the PostSynchronizationScriptPath field.
func (o *DesktopPoolQuickprepCustomizationSettings) SetPostSynchronizationScriptPath(v string) {
	o.PostSynchronizationScriptPath = &v
}

// GetPowerOffScriptParameters returns the PowerOffScriptParameters field value if set, zero value otherwise.
func (o *DesktopPoolQuickprepCustomizationSettings) GetPowerOffScriptParameters() string {
	if o == nil || IsNil(o.PowerOffScriptParameters) {
		var ret string
		return ret
	}
	return *o.PowerOffScriptParameters
}

// GetPowerOffScriptParametersOk returns a tuple with the PowerOffScriptParameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DesktopPoolQuickprepCustomizationSettings) GetPowerOffScriptParametersOk() (*string, bool) {
	if o == nil || IsNil(o.PowerOffScriptParameters) {
		return nil, false
	}
	return o.PowerOffScriptParameters, true
}

// HasPowerOffScriptParameters returns a boolean if a field has been set.
func (o *DesktopPoolQuickprepCustomizationSettings) HasPowerOffScriptParameters() bool {
	if o != nil && !IsNil(o.PowerOffScriptParameters) {
		return true
	}

	return false
}

// SetPowerOffScriptParameters gets a reference to the given string and assigns it to the PowerOffScriptParameters field.
func (o *DesktopPoolQuickprepCustomizationSettings) SetPowerOffScriptParameters(v string) {
	o.PowerOffScriptParameters = &v
}

// GetPowerOffScriptPath returns the PowerOffScriptPath field value if set, zero value otherwise.
func (o *DesktopPoolQuickprepCustomizationSettings) GetPowerOffScriptPath() string {
	if o == nil || IsNil(o.PowerOffScriptPath) {
		var ret string
		return ret
	}
	return *o.PowerOffScriptPath
}

// GetPowerOffScriptPathOk returns a tuple with the PowerOffScriptPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DesktopPoolQuickprepCustomizationSettings) GetPowerOffScriptPathOk() (*string, bool) {
	if o == nil || IsNil(o.PowerOffScriptPath) {
		return nil, false
	}
	return o.PowerOffScriptPath, true
}

// HasPowerOffScriptPath returns a boolean if a field has been set.
func (o *DesktopPoolQuickprepCustomizationSettings) HasPowerOffScriptPath() bool {
	if o != nil && !IsNil(o.PowerOffScriptPath) {
		return true
	}

	return false
}

// SetPowerOffScriptPath gets a reference to the given string and assigns it to the PowerOffScriptPath field.
func (o *DesktopPoolQuickprepCustomizationSettings) SetPowerOffScriptPath(v string) {
	o.PowerOffScriptPath = &v
}

func (o DesktopPoolQuickprepCustomizationSettings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DesktopPoolQuickprepCustomizationSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PostSynchronizationScriptParameters) {
		toSerialize["post_synchronization_script_parameters"] = o.PostSynchronizationScriptParameters
	}
	if !IsNil(o.PostSynchronizationScriptPath) {
		toSerialize["post_synchronization_script_path"] = o.PostSynchronizationScriptPath
	}
	if !IsNil(o.PowerOffScriptParameters) {
		toSerialize["power_off_script_parameters"] = o.PowerOffScriptParameters
	}
	if !IsNil(o.PowerOffScriptPath) {
		toSerialize["power_off_script_path"] = o.PowerOffScriptPath
	}
	return toSerialize, nil
}

type NullableDesktopPoolQuickprepCustomizationSettings struct {
	value *DesktopPoolQuickprepCustomizationSettings
	isSet bool
}

func (v NullableDesktopPoolQuickprepCustomizationSettings) Get() *DesktopPoolQuickprepCustomizationSettings {
	return v.value
}

func (v *NullableDesktopPoolQuickprepCustomizationSettings) Set(val *DesktopPoolQuickprepCustomizationSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableDesktopPoolQuickprepCustomizationSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableDesktopPoolQuickprepCustomizationSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDesktopPoolQuickprepCustomizationSettings(val *DesktopPoolQuickprepCustomizationSettings) *NullableDesktopPoolQuickprepCustomizationSettings {
	return &NullableDesktopPoolQuickprepCustomizationSettings{value: val, isSet: true}
}

func (v NullableDesktopPoolQuickprepCustomizationSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDesktopPoolQuickprepCustomizationSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


