/*
Horizon Server API

Welcome to the Horizon Server API Reference documentation. This API reference provides comprehensive information about status of all Horizon Server components and resources. <br> Choose Latest spec from dropdown to view API reference on latest version available.

API version: 2212
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gohorizon

import (
	"encoding/json"
)

// checks if the RDSHLoadBalancerSettingsInfoV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RDSHLoadBalancerSettingsInfoV2{}

// RDSHLoadBalancerSettingsInfoV2 RDSH load balancer settings for the farm.
type RDSHLoadBalancerSettingsInfoV2 struct {
	// Represents the maximum number of sessions that can concurrently log into each RDSH agent machine in the farm, exempting reconnecting sessions.
	ConnectingSessionThreshold *int32 `json:"connecting_session_threshold,omitempty"`
	// Represents threshold of CPU usage, in percentage. If the value is 0, then this metric is not considered for load balancing.
	CpuThreshold *int32 `json:"cpu_threshold,omitempty"`
	// Represents the threshold of average number of both read and write requests that were queued for the selected disk during the sample interval. If the value is 0, then this metric is not considered for load balancing.
	DiskQueueLengthThreshold *int32 `json:"disk_queue_length_threshold,omitempty"`
	// Represents the threshold of average time, in milliseconds, of a read of data from the disk. If the value is 0, then this metric is not considered for load balancing. 
	DiskReadLatencyThreshold *int32 `json:"disk_read_latency_threshold,omitempty"`
	// Represents the threshold of average time, in milliseconds, of a write of data to the disk. If the value is 0, then this metric is not considered for load balancing.
	DiskWriteLatencyThreshold *int32 `json:"disk_write_latency_threshold,omitempty"`
	// Indicates whether to include session count for load balancing.
	IncludeSessionCount *bool `json:"include_session_count,omitempty"`
	// Represents the minimum load index at which each RDSH agent machine in the farm will start denying session logins, exempting reconnecting sessions.
	LoadIndexThreshold *int32 `json:"load_index_threshold,omitempty"`
	// Represents threshold of memory usage, in percentage. If the value is 0, then this metric is not considered for load balancing. 
	MemoryThreshold *int32 `json:"memory_threshold,omitempty"`
}

// NewRDSHLoadBalancerSettingsInfoV2 instantiates a new RDSHLoadBalancerSettingsInfoV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRDSHLoadBalancerSettingsInfoV2() *RDSHLoadBalancerSettingsInfoV2 {
	this := RDSHLoadBalancerSettingsInfoV2{}
	return &this
}

// NewRDSHLoadBalancerSettingsInfoV2WithDefaults instantiates a new RDSHLoadBalancerSettingsInfoV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRDSHLoadBalancerSettingsInfoV2WithDefaults() *RDSHLoadBalancerSettingsInfoV2 {
	this := RDSHLoadBalancerSettingsInfoV2{}
	return &this
}

// GetConnectingSessionThreshold returns the ConnectingSessionThreshold field value if set, zero value otherwise.
func (o *RDSHLoadBalancerSettingsInfoV2) GetConnectingSessionThreshold() int32 {
	if o == nil || IsNil(o.ConnectingSessionThreshold) {
		var ret int32
		return ret
	}
	return *o.ConnectingSessionThreshold
}

// GetConnectingSessionThresholdOk returns a tuple with the ConnectingSessionThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RDSHLoadBalancerSettingsInfoV2) GetConnectingSessionThresholdOk() (*int32, bool) {
	if o == nil || IsNil(o.ConnectingSessionThreshold) {
		return nil, false
	}
	return o.ConnectingSessionThreshold, true
}

// HasConnectingSessionThreshold returns a boolean if a field has been set.
func (o *RDSHLoadBalancerSettingsInfoV2) HasConnectingSessionThreshold() bool {
	if o != nil && !IsNil(o.ConnectingSessionThreshold) {
		return true
	}

	return false
}

// SetConnectingSessionThreshold gets a reference to the given int32 and assigns it to the ConnectingSessionThreshold field.
func (o *RDSHLoadBalancerSettingsInfoV2) SetConnectingSessionThreshold(v int32) {
	o.ConnectingSessionThreshold = &v
}

// GetCpuThreshold returns the CpuThreshold field value if set, zero value otherwise.
func (o *RDSHLoadBalancerSettingsInfoV2) GetCpuThreshold() int32 {
	if o == nil || IsNil(o.CpuThreshold) {
		var ret int32
		return ret
	}
	return *o.CpuThreshold
}

// GetCpuThresholdOk returns a tuple with the CpuThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RDSHLoadBalancerSettingsInfoV2) GetCpuThresholdOk() (*int32, bool) {
	if o == nil || IsNil(o.CpuThreshold) {
		return nil, false
	}
	return o.CpuThreshold, true
}

// HasCpuThreshold returns a boolean if a field has been set.
func (o *RDSHLoadBalancerSettingsInfoV2) HasCpuThreshold() bool {
	if o != nil && !IsNil(o.CpuThreshold) {
		return true
	}

	return false
}

// SetCpuThreshold gets a reference to the given int32 and assigns it to the CpuThreshold field.
func (o *RDSHLoadBalancerSettingsInfoV2) SetCpuThreshold(v int32) {
	o.CpuThreshold = &v
}

// GetDiskQueueLengthThreshold returns the DiskQueueLengthThreshold field value if set, zero value otherwise.
func (o *RDSHLoadBalancerSettingsInfoV2) GetDiskQueueLengthThreshold() int32 {
	if o == nil || IsNil(o.DiskQueueLengthThreshold) {
		var ret int32
		return ret
	}
	return *o.DiskQueueLengthThreshold
}

// GetDiskQueueLengthThresholdOk returns a tuple with the DiskQueueLengthThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RDSHLoadBalancerSettingsInfoV2) GetDiskQueueLengthThresholdOk() (*int32, bool) {
	if o == nil || IsNil(o.DiskQueueLengthThreshold) {
		return nil, false
	}
	return o.DiskQueueLengthThreshold, true
}

// HasDiskQueueLengthThreshold returns a boolean if a field has been set.
func (o *RDSHLoadBalancerSettingsInfoV2) HasDiskQueueLengthThreshold() bool {
	if o != nil && !IsNil(o.DiskQueueLengthThreshold) {
		return true
	}

	return false
}

// SetDiskQueueLengthThreshold gets a reference to the given int32 and assigns it to the DiskQueueLengthThreshold field.
func (o *RDSHLoadBalancerSettingsInfoV2) SetDiskQueueLengthThreshold(v int32) {
	o.DiskQueueLengthThreshold = &v
}

// GetDiskReadLatencyThreshold returns the DiskReadLatencyThreshold field value if set, zero value otherwise.
func (o *RDSHLoadBalancerSettingsInfoV2) GetDiskReadLatencyThreshold() int32 {
	if o == nil || IsNil(o.DiskReadLatencyThreshold) {
		var ret int32
		return ret
	}
	return *o.DiskReadLatencyThreshold
}

// GetDiskReadLatencyThresholdOk returns a tuple with the DiskReadLatencyThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RDSHLoadBalancerSettingsInfoV2) GetDiskReadLatencyThresholdOk() (*int32, bool) {
	if o == nil || IsNil(o.DiskReadLatencyThreshold) {
		return nil, false
	}
	return o.DiskReadLatencyThreshold, true
}

// HasDiskReadLatencyThreshold returns a boolean if a field has been set.
func (o *RDSHLoadBalancerSettingsInfoV2) HasDiskReadLatencyThreshold() bool {
	if o != nil && !IsNil(o.DiskReadLatencyThreshold) {
		return true
	}

	return false
}

// SetDiskReadLatencyThreshold gets a reference to the given int32 and assigns it to the DiskReadLatencyThreshold field.
func (o *RDSHLoadBalancerSettingsInfoV2) SetDiskReadLatencyThreshold(v int32) {
	o.DiskReadLatencyThreshold = &v
}

// GetDiskWriteLatencyThreshold returns the DiskWriteLatencyThreshold field value if set, zero value otherwise.
func (o *RDSHLoadBalancerSettingsInfoV2) GetDiskWriteLatencyThreshold() int32 {
	if o == nil || IsNil(o.DiskWriteLatencyThreshold) {
		var ret int32
		return ret
	}
	return *o.DiskWriteLatencyThreshold
}

// GetDiskWriteLatencyThresholdOk returns a tuple with the DiskWriteLatencyThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RDSHLoadBalancerSettingsInfoV2) GetDiskWriteLatencyThresholdOk() (*int32, bool) {
	if o == nil || IsNil(o.DiskWriteLatencyThreshold) {
		return nil, false
	}
	return o.DiskWriteLatencyThreshold, true
}

// HasDiskWriteLatencyThreshold returns a boolean if a field has been set.
func (o *RDSHLoadBalancerSettingsInfoV2) HasDiskWriteLatencyThreshold() bool {
	if o != nil && !IsNil(o.DiskWriteLatencyThreshold) {
		return true
	}

	return false
}

// SetDiskWriteLatencyThreshold gets a reference to the given int32 and assigns it to the DiskWriteLatencyThreshold field.
func (o *RDSHLoadBalancerSettingsInfoV2) SetDiskWriteLatencyThreshold(v int32) {
	o.DiskWriteLatencyThreshold = &v
}

// GetIncludeSessionCount returns the IncludeSessionCount field value if set, zero value otherwise.
func (o *RDSHLoadBalancerSettingsInfoV2) GetIncludeSessionCount() bool {
	if o == nil || IsNil(o.IncludeSessionCount) {
		var ret bool
		return ret
	}
	return *o.IncludeSessionCount
}

// GetIncludeSessionCountOk returns a tuple with the IncludeSessionCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RDSHLoadBalancerSettingsInfoV2) GetIncludeSessionCountOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludeSessionCount) {
		return nil, false
	}
	return o.IncludeSessionCount, true
}

// HasIncludeSessionCount returns a boolean if a field has been set.
func (o *RDSHLoadBalancerSettingsInfoV2) HasIncludeSessionCount() bool {
	if o != nil && !IsNil(o.IncludeSessionCount) {
		return true
	}

	return false
}

// SetIncludeSessionCount gets a reference to the given bool and assigns it to the IncludeSessionCount field.
func (o *RDSHLoadBalancerSettingsInfoV2) SetIncludeSessionCount(v bool) {
	o.IncludeSessionCount = &v
}

// GetLoadIndexThreshold returns the LoadIndexThreshold field value if set, zero value otherwise.
func (o *RDSHLoadBalancerSettingsInfoV2) GetLoadIndexThreshold() int32 {
	if o == nil || IsNil(o.LoadIndexThreshold) {
		var ret int32
		return ret
	}
	return *o.LoadIndexThreshold
}

// GetLoadIndexThresholdOk returns a tuple with the LoadIndexThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RDSHLoadBalancerSettingsInfoV2) GetLoadIndexThresholdOk() (*int32, bool) {
	if o == nil || IsNil(o.LoadIndexThreshold) {
		return nil, false
	}
	return o.LoadIndexThreshold, true
}

// HasLoadIndexThreshold returns a boolean if a field has been set.
func (o *RDSHLoadBalancerSettingsInfoV2) HasLoadIndexThreshold() bool {
	if o != nil && !IsNil(o.LoadIndexThreshold) {
		return true
	}

	return false
}

// SetLoadIndexThreshold gets a reference to the given int32 and assigns it to the LoadIndexThreshold field.
func (o *RDSHLoadBalancerSettingsInfoV2) SetLoadIndexThreshold(v int32) {
	o.LoadIndexThreshold = &v
}

// GetMemoryThreshold returns the MemoryThreshold field value if set, zero value otherwise.
func (o *RDSHLoadBalancerSettingsInfoV2) GetMemoryThreshold() int32 {
	if o == nil || IsNil(o.MemoryThreshold) {
		var ret int32
		return ret
	}
	return *o.MemoryThreshold
}

// GetMemoryThresholdOk returns a tuple with the MemoryThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RDSHLoadBalancerSettingsInfoV2) GetMemoryThresholdOk() (*int32, bool) {
	if o == nil || IsNil(o.MemoryThreshold) {
		return nil, false
	}
	return o.MemoryThreshold, true
}

// HasMemoryThreshold returns a boolean if a field has been set.
func (o *RDSHLoadBalancerSettingsInfoV2) HasMemoryThreshold() bool {
	if o != nil && !IsNil(o.MemoryThreshold) {
		return true
	}

	return false
}

// SetMemoryThreshold gets a reference to the given int32 and assigns it to the MemoryThreshold field.
func (o *RDSHLoadBalancerSettingsInfoV2) SetMemoryThreshold(v int32) {
	o.MemoryThreshold = &v
}

func (o RDSHLoadBalancerSettingsInfoV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RDSHLoadBalancerSettingsInfoV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ConnectingSessionThreshold) {
		toSerialize["connecting_session_threshold"] = o.ConnectingSessionThreshold
	}
	if !IsNil(o.CpuThreshold) {
		toSerialize["cpu_threshold"] = o.CpuThreshold
	}
	if !IsNil(o.DiskQueueLengthThreshold) {
		toSerialize["disk_queue_length_threshold"] = o.DiskQueueLengthThreshold
	}
	if !IsNil(o.DiskReadLatencyThreshold) {
		toSerialize["disk_read_latency_threshold"] = o.DiskReadLatencyThreshold
	}
	if !IsNil(o.DiskWriteLatencyThreshold) {
		toSerialize["disk_write_latency_threshold"] = o.DiskWriteLatencyThreshold
	}
	if !IsNil(o.IncludeSessionCount) {
		toSerialize["include_session_count"] = o.IncludeSessionCount
	}
	if !IsNil(o.LoadIndexThreshold) {
		toSerialize["load_index_threshold"] = o.LoadIndexThreshold
	}
	if !IsNil(o.MemoryThreshold) {
		toSerialize["memory_threshold"] = o.MemoryThreshold
	}
	return toSerialize, nil
}

type NullableRDSHLoadBalancerSettingsInfoV2 struct {
	value *RDSHLoadBalancerSettingsInfoV2
	isSet bool
}

func (v NullableRDSHLoadBalancerSettingsInfoV2) Get() *RDSHLoadBalancerSettingsInfoV2 {
	return v.value
}

func (v *NullableRDSHLoadBalancerSettingsInfoV2) Set(val *RDSHLoadBalancerSettingsInfoV2) {
	v.value = val
	v.isSet = true
}

func (v NullableRDSHLoadBalancerSettingsInfoV2) IsSet() bool {
	return v.isSet
}

func (v *NullableRDSHLoadBalancerSettingsInfoV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRDSHLoadBalancerSettingsInfoV2(val *RDSHLoadBalancerSettingsInfoV2) *NullableRDSHLoadBalancerSettingsInfoV2 {
	return &NullableRDSHLoadBalancerSettingsInfoV2{value: val, isSet: true}
}

func (v NullableRDSHLoadBalancerSettingsInfoV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRDSHLoadBalancerSettingsInfoV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


