/*
Horizon Server API

Welcome to the Horizon Server API Reference documentation. This API reference provides comprehensive information about status of all Horizon Server components and resources. <br> Choose Latest spec from dropdown to view API reference on latest version available.

API version: 2212
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gohorizon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FarmNetworkLabelAssignmentSettingsUpdateSpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FarmNetworkLabelAssignmentSettingsUpdateSpec{}

// FarmNetworkLabelAssignmentSettingsUpdateSpec Network label assignment settings for the farm.
type FarmNetworkLabelAssignmentSettingsUpdateSpec struct {
	// Indicates whether or not this specification is enabled. While this specification is disabled, automatic network label assignment for this automated farm will skip over the network label in this spec.
	Enabled bool `json:"enabled"`
	// The maximum number of times this label can be assigned to a RDS server. Note this count only encompasses this spec. That is, this label may be used for other NICs and in other farms, but those assignments will not be counted towards this total. This count also does not include assignments of this label to RDS server not under the control of View. This is required if max_label_type is set to LIMITED.
	MaxLabel *int32 `json:"max_label,omitempty"`
	// This type specifies whether or not there is a maximum limit to the number of times this label may be assigned to machines within this spec. While this specification is enabled and unlimited, specs after this one in the NIC's network label specification list will never be used. * UNLIMITED: The network label assignment specification has no limit on the number of labels to assign. * LIMITED: The network label assignment specification has a limited number of labels to assign.
	MaxLabelType string `json:"max_label_type"`
	// The network label id for this spec. This network label must not have any incompatibility reasons that would preclude it from automatic machine assignment.
	NetworkLabelName string `json:"network_label_name"`
}

type _FarmNetworkLabelAssignmentSettingsUpdateSpec FarmNetworkLabelAssignmentSettingsUpdateSpec

// NewFarmNetworkLabelAssignmentSettingsUpdateSpec instantiates a new FarmNetworkLabelAssignmentSettingsUpdateSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFarmNetworkLabelAssignmentSettingsUpdateSpec(enabled bool, maxLabelType string, networkLabelName string) *FarmNetworkLabelAssignmentSettingsUpdateSpec {
	this := FarmNetworkLabelAssignmentSettingsUpdateSpec{}
	this.Enabled = enabled
	this.MaxLabelType = maxLabelType
	this.NetworkLabelName = networkLabelName
	return &this
}

// NewFarmNetworkLabelAssignmentSettingsUpdateSpecWithDefaults instantiates a new FarmNetworkLabelAssignmentSettingsUpdateSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFarmNetworkLabelAssignmentSettingsUpdateSpecWithDefaults() *FarmNetworkLabelAssignmentSettingsUpdateSpec {
	this := FarmNetworkLabelAssignmentSettingsUpdateSpec{}
	return &this
}

// GetEnabled returns the Enabled field value
func (o *FarmNetworkLabelAssignmentSettingsUpdateSpec) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *FarmNetworkLabelAssignmentSettingsUpdateSpec) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *FarmNetworkLabelAssignmentSettingsUpdateSpec) SetEnabled(v bool) {
	o.Enabled = v
}

// GetMaxLabel returns the MaxLabel field value if set, zero value otherwise.
func (o *FarmNetworkLabelAssignmentSettingsUpdateSpec) GetMaxLabel() int32 {
	if o == nil || IsNil(o.MaxLabel) {
		var ret int32
		return ret
	}
	return *o.MaxLabel
}

// GetMaxLabelOk returns a tuple with the MaxLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FarmNetworkLabelAssignmentSettingsUpdateSpec) GetMaxLabelOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxLabel) {
		return nil, false
	}
	return o.MaxLabel, true
}

// HasMaxLabel returns a boolean if a field has been set.
func (o *FarmNetworkLabelAssignmentSettingsUpdateSpec) HasMaxLabel() bool {
	if o != nil && !IsNil(o.MaxLabel) {
		return true
	}

	return false
}

// SetMaxLabel gets a reference to the given int32 and assigns it to the MaxLabel field.
func (o *FarmNetworkLabelAssignmentSettingsUpdateSpec) SetMaxLabel(v int32) {
	o.MaxLabel = &v
}

// GetMaxLabelType returns the MaxLabelType field value
func (o *FarmNetworkLabelAssignmentSettingsUpdateSpec) GetMaxLabelType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MaxLabelType
}

// GetMaxLabelTypeOk returns a tuple with the MaxLabelType field value
// and a boolean to check if the value has been set.
func (o *FarmNetworkLabelAssignmentSettingsUpdateSpec) GetMaxLabelTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxLabelType, true
}

// SetMaxLabelType sets field value
func (o *FarmNetworkLabelAssignmentSettingsUpdateSpec) SetMaxLabelType(v string) {
	o.MaxLabelType = v
}

// GetNetworkLabelName returns the NetworkLabelName field value
func (o *FarmNetworkLabelAssignmentSettingsUpdateSpec) GetNetworkLabelName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NetworkLabelName
}

// GetNetworkLabelNameOk returns a tuple with the NetworkLabelName field value
// and a boolean to check if the value has been set.
func (o *FarmNetworkLabelAssignmentSettingsUpdateSpec) GetNetworkLabelNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NetworkLabelName, true
}

// SetNetworkLabelName sets field value
func (o *FarmNetworkLabelAssignmentSettingsUpdateSpec) SetNetworkLabelName(v string) {
	o.NetworkLabelName = v
}

func (o FarmNetworkLabelAssignmentSettingsUpdateSpec) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FarmNetworkLabelAssignmentSettingsUpdateSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["enabled"] = o.Enabled
	if !IsNil(o.MaxLabel) {
		toSerialize["max_label"] = o.MaxLabel
	}
	toSerialize["max_label_type"] = o.MaxLabelType
	toSerialize["network_label_name"] = o.NetworkLabelName
	return toSerialize, nil
}

func (o *FarmNetworkLabelAssignmentSettingsUpdateSpec) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"enabled",
		"max_label_type",
		"network_label_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFarmNetworkLabelAssignmentSettingsUpdateSpec := _FarmNetworkLabelAssignmentSettingsUpdateSpec{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFarmNetworkLabelAssignmentSettingsUpdateSpec)

	if err != nil {
		return err
	}

	*o = FarmNetworkLabelAssignmentSettingsUpdateSpec(varFarmNetworkLabelAssignmentSettingsUpdateSpec)

	return err
}

type NullableFarmNetworkLabelAssignmentSettingsUpdateSpec struct {
	value *FarmNetworkLabelAssignmentSettingsUpdateSpec
	isSet bool
}

func (v NullableFarmNetworkLabelAssignmentSettingsUpdateSpec) Get() *FarmNetworkLabelAssignmentSettingsUpdateSpec {
	return v.value
}

func (v *NullableFarmNetworkLabelAssignmentSettingsUpdateSpec) Set(val *FarmNetworkLabelAssignmentSettingsUpdateSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableFarmNetworkLabelAssignmentSettingsUpdateSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableFarmNetworkLabelAssignmentSettingsUpdateSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFarmNetworkLabelAssignmentSettingsUpdateSpec(val *FarmNetworkLabelAssignmentSettingsUpdateSpec) *NullableFarmNetworkLabelAssignmentSettingsUpdateSpec {
	return &NullableFarmNetworkLabelAssignmentSettingsUpdateSpec{value: val, isSet: true}
}

func (v NullableFarmNetworkLabelAssignmentSettingsUpdateSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFarmNetworkLabelAssignmentSettingsUpdateSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


