/*
Horizon Server API

Welcome to the Horizon Server API Reference documentation. This API reference provides comprehensive information about status of all Horizon Server components and resources. <br> Choose Latest spec from dropdown to view API reference on latest version available.

API version: 2212
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gohorizon

import (
	"encoding/json"
)

// checks if the ADDomainInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ADDomainInfo{}

// ADDomainInfo Information related to AD Domains of the environment.
type ADDomainInfo struct {
	// DNS name of the AD Domain.
	DnsName *string `json:"dns_name,omitempty"`
	// Unique SID representing AD Domain.
	Id *string `json:"id,omitempty"`
	// NetBIOS name of the AD Domain.
	NetbiosName *string `json:"netbios_name,omitempty"`
}

// NewADDomainInfo instantiates a new ADDomainInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewADDomainInfo() *ADDomainInfo {
	this := ADDomainInfo{}
	return &this
}

// NewADDomainInfoWithDefaults instantiates a new ADDomainInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewADDomainInfoWithDefaults() *ADDomainInfo {
	this := ADDomainInfo{}
	return &this
}

// GetDnsName returns the DnsName field value if set, zero value otherwise.
func (o *ADDomainInfo) GetDnsName() string {
	if o == nil || IsNil(o.DnsName) {
		var ret string
		return ret
	}
	return *o.DnsName
}

// GetDnsNameOk returns a tuple with the DnsName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ADDomainInfo) GetDnsNameOk() (*string, bool) {
	if o == nil || IsNil(o.DnsName) {
		return nil, false
	}
	return o.DnsName, true
}

// HasDnsName returns a boolean if a field has been set.
func (o *ADDomainInfo) HasDnsName() bool {
	if o != nil && !IsNil(o.DnsName) {
		return true
	}

	return false
}

// SetDnsName gets a reference to the given string and assigns it to the DnsName field.
func (o *ADDomainInfo) SetDnsName(v string) {
	o.DnsName = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ADDomainInfo) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ADDomainInfo) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ADDomainInfo) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ADDomainInfo) SetId(v string) {
	o.Id = &v
}

// GetNetbiosName returns the NetbiosName field value if set, zero value otherwise.
func (o *ADDomainInfo) GetNetbiosName() string {
	if o == nil || IsNil(o.NetbiosName) {
		var ret string
		return ret
	}
	return *o.NetbiosName
}

// GetNetbiosNameOk returns a tuple with the NetbiosName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ADDomainInfo) GetNetbiosNameOk() (*string, bool) {
	if o == nil || IsNil(o.NetbiosName) {
		return nil, false
	}
	return o.NetbiosName, true
}

// HasNetbiosName returns a boolean if a field has been set.
func (o *ADDomainInfo) HasNetbiosName() bool {
	if o != nil && !IsNil(o.NetbiosName) {
		return true
	}

	return false
}

// SetNetbiosName gets a reference to the given string and assigns it to the NetbiosName field.
func (o *ADDomainInfo) SetNetbiosName(v string) {
	o.NetbiosName = &v
}

func (o ADDomainInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ADDomainInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DnsName) {
		toSerialize["dns_name"] = o.DnsName
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.NetbiosName) {
		toSerialize["netbios_name"] = o.NetbiosName
	}
	return toSerialize, nil
}

type NullableADDomainInfo struct {
	value *ADDomainInfo
	isSet bool
}

func (v NullableADDomainInfo) Get() *ADDomainInfo {
	return v.value
}

func (v *NullableADDomainInfo) Set(val *ADDomainInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableADDomainInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableADDomainInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableADDomainInfo(val *ADDomainInfo) *NullableADDomainInfo {
	return &NullableADDomainInfo{value: val, isSet: true}
}

func (v NullableADDomainInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableADDomainInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


